language: node_js
node_js:
  - '0.8'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - 'grunt build'
deploy:
  provider: heroku
  app: jensoleg
  api_key: "35efbe8ca8597471b7aa0b2c23fc9458b730f855"
